spring:
  application:
    name: order-processing-demo
  thymeleaf:
    cache: false

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

# enable all actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring.mvc:
  view:
    prefix: /WEB-INF/views/
    suffix: .jsp

aws:
  sqs:
    queueName: OrderQueue
    region: ap-southeast-2
  sns:
    topicName: OrderNotifications
    region: ap-southeast-2

testmode: true